version: '3.8'
services:
    scanner:
        # profiles:
        #     - donotstart
        build:
            context: ./scanner
            dockerfile: Dockerfile
        environment:
            - CONTRACT_ADDRESS=$CONTRACT_ADDRESS
            - NODE_ENDPOINT=$NODE_ENDPOINT
            - DB_HOST=$DB_HOST
            - DB_USERNAME=$DB_USERNAME
            - DB_PASSWORD=$DB_PASSWORD
            - SCAN_CHUNK_SIZE=$SCAN_CHUNK_SIZE
            - SCAN_START_BLOCK=$SCAN_START_BLOCK
        volumes:
            - "./scanner/src:/app/src"
        # ports:
        #     - "8081:8081"
        healthcheck:
            test: "node -v"
            interval: 10s
            start_period: 5s
            timeout: 5s
            retries: 5
        depends_on:
            postgres:
                condition: service_healthy
            # ethereum-node:
            #     condition: service_healthy
    graphql:
        # profiles:
        #     - donotstart
        build:
            context: ./graphql
            dockerfile: Dockerfile
        environment:
            - SERVER_PORT=$SERVER_PORT
            - DB_HOST=$DB_HOST
            - DB_USERNAME=$DB_USERNAME
            - DB_PASSWORD=$DB_PASSWORD
        volumes:
            - "./graphql/src:/app/src"
        ports:
            - "80085:80085"
        depends_on:
            postgres:
                condition: service_healthy
            scanner:
                condition: service_healthy
    postgres:
        # profiles:
        #     - donotstart
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=$PG_USERNAME
            - POSTGRES_PASSWORD=$PG_PASSWORD
            - APP_DB_USER=$DB_USERNAME
            - APP_DB_PASS=$DB_PASSWORD
            - APP_DB_NAME=$DB_NAME
        logging:
          options:
            max-size: 10m
            max-file: "3"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - "5432:5432"
        volumes: 
          - ./postgresql_data:/var/lib/postgresql/data
          - ./models/init_db/create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
