version: '3.8'
services:
    scanner:
        # profiles:
        #     - donotstart
        build:
            context: ./scanner
            dockerfile: Dockerfile
        environment:
            - CONTRACT_ADDRESS=$CONTRACT_ADDRESS
            - NODE_ENDPOINT=$NODE_ENDPOINT
            - DB_HOST=$DB_HOST
            - DB_USERNAME=$DB_USERNAME
            - DB_PASSWORD=$DB_PASSWORD
        # volumes:
        #     - "./scanner/src:/app/src"
        ports:
            - "8081:8081"
        depends_on:
            - postgres
    graphql:
        # profiles:
        #     - donotstart
        build:
            context: ./graphql
            dockerfile: Dockerfile
        environment:
            - SERVER_PORT=$SERVER_PORT
            - DB_HOST=$DB_HOST
            - DB_USERNAME=$DB_USERNAME
            - DB_PASSWORD=$DB_PASSWORD
        # volumes:
        #     - "./graphql/src:/app/src"
        ports:
            - "8082:8082"
        depends_on:
            - postgres
            - scanner
    postgres:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=$PG_USERNAME
            - POSTGRES_PASSWORD=$PG_PASSWORD
            - APP_DB_USER=$DB_USERNAME
            - APP_DB_PASS=$DB_PASSWORD
            - APP_DB_NAME=$DB_NAME
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
            - "5432:5432"
        volumes: 
          - ./postgresql_data:/var/lib/postgresql/data
          - ./models/init_db/create_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
